name: Create new d-compat branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    permissions:
      contents: write
    uses: discourse/.github/.github/workflows/create-d-compat-branch.yml@v1
